title: Bits & Backprops
tagline: Where git commits meet gradients
author:
  name: Yudhiesh Ravindranath
  email: yudhiesh1997@gmail.com
description: >- 
  Where git commits meet gradients. Tales of engineering clean code 
  and neural nets, minus the academic jargon.
baseurl: "" 
url: "https://yudhiesh.github.io"

permalink: /:year/:month/:day/:title/

social:
  name: Yudhiesh Ravindranath
  links:
    - https://github.com/yudhiesh
    - https://www.linkedin.com/in/yudhiesh-ravindranath/

twitter:
  username: yudhiesh1997
  card: summary

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Yudhiesh Ravindranath"

minima:
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/yudhiesh"
    - title: LinkedIn
      icon: x-linkedin
      url: "https://www.linkedin.com/in/yudhiesh-ravindranath/"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  mathjax:
    path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML

remote_theme: jekyll/minima@0b7ca6bbdb782a646f8e7b78b1a29fd5032ad4d3
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  
minima:
  skin: auto

sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/404.html"
    - "/feed.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - src/
  - "*.markdown"  # Don't include raw markdown files
  - "*.md"  # Don't include raw markdown files
  - README.md
  - LICENSE
  - CNAME
